import DisplayWindow from '@/components/layout/displayWindow';
import moment from 'moment';
import { Metadata } from 'next';
import Link from 'next/link';
import { getAllProjects } from '../../../lib/api';

export const metadata: Metadata = {
	title: 'robbarton.dev | projects',
	description: 'Generated by create next app',
};

export default function Projects() {
	const projects = getAllProjects();

	return (
		<DisplayWindow pageLocation="/projects">
			<table className="prose-sm w-full max-w-none md:prose md:max-w-none">
				<thead className="text-left">
					<tr>
						<th>name</th>
						<th>description</th>
						<th>date</th>
					</tr>
				</thead>
				<tbody>
					{projects.map((project, id) => (
						<tr key={id}>
							<td className="underline">
								<Link href={`projects/${project.slug}`}>{project.title}</Link>
							</td>
							<td>{project.description}</td>
							<td>{moment(project.date).format('MM/YY')}</td>
						</tr>
					))}
				</tbody>
			</table>
		</DisplayWindow>
	);
}
